---
abstract: 'A POE Component to query NTP servers'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
  - 'James G. Willmore'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NTP
requires:
  IO::Socket::INET: 0
  Net::IP: 0
  POE: 1.004
  Socket: 0
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/poe-component-client-ntp
  repository: https://github.com/bingos/poe-component-client-ntp
version: 0.04
