---
abstract: 'A POE Component to query NTP servers'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NTP
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  IO::Socket::INET: 0
  Net::IP: 0
  POE: 1.004
  Socket: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-ntp.git
version: 0.02
